### ISSUE TITLE
Fix MSMBuilder build error

### ISSUE THREAD

**Issue by dwhswenson** [choderalab/opentis#100]
Conda now defaults to MSMB3, which does not have the `metrics` package, breaking Travis builds because `orderparameter.py` calls for `msmbuilder.metrics`.

This was given a temporary fix in #93 by fixing msmbuilder version to an old version (the same one I got through pip a while ago). This is not the best solution, so something better should be done.

Assigning to @jhprinz, since the MSM side of things is his expertise, and he can more easily correct the existing code.

**Comment by jhprinz** [comment]
This was fixed by the PR #107 .

**Comment by jhprinz** [comment]
Closing
