### ISSUE TITLE
Renaming MoveDetails attributes

### ISSUE THREAD

**Issue by dwhswenson** [choderalab/opentis#102]
I think the current names of the `MoveDetails` attributes are a bit confusing. Before we get too far into making more `PathMover`s, I'd like to change some of those names. In particular, I think `final` vs `result` is a little unclear, and `success` vs `accepted` vs `acceptance` is unclear.

Here are my suggestions, in the format `oldname => newname` : description

Things to change:

* `final => trial` : a `Trajectory` representing the trial trajectory (what will go to the output sample if the move is accepted)
* `acceptance => acceptance_probability` : the probability of accepting this step (i.e., Metropolis acceptance probability). Note that for many moves, this is 1 or 0.
* `accepted => trial_is_in_ensemble` : this seems to only be the test of whether the trial path in a shooting move is in the correct ensemble. Unless I'm misunderstanding, it should be moved out of general move details, and only exist for shooting movers.
* `success => accepted` : whether the trial is accepted by the Monte Carlo method

Things to keep the same:

* `inputs => inputs` : list of the `Sample`s selected to be used in the move
* `result => result` : the `Sample` that gets returned by the move
* `mover => mover` : the `PathMover` which generated these details

Note that right now, the things I say are `Sample`s are actually `Trajectory` objects. For now, I'm leaving them as `Trajectory`, but I think we might want to change that to `Sample` eventually. (Should `result` be a `Sample` which is recursively referential, or should it be the `Trajectory` of that sample? Gets weird when thinking about `EnsembleHopMover`s, where the `Trajectory` doesn't change.) 

Any other thoughts on these names? Suggestions for better names to use?

**Comment by jhprinz** [comment]
Never commented on this. Yes, it sounds good!
