### ISSUE TITLE
Set up automated travis pushing of docs Amazon S3 bucket

### ISSUE THREAD

**Issue by jchodera** [choderalab/opentis#113]
I've created an S3 bucket called `openpathsampling` that we will have `openpathsampling.org` point to, much like http://mdtraj.org does now.  

@pgrinaway can help configure this.

**Comment by jhprinz** [comment]
Apparently the bucket is set up. Still need to add the push to s3 using the secure token.

**Comment by jchodera** [comment]
@pgrinaway should be able to help with that.

**Comment by jchodera** [comment]
This works now.  Check it out:

http://openpathsampling.org
