### ISSUE TITLE
S3 bucket index.html redirects to latest/index.html

### ISSUE THREAD

**Issue by jchodera** [choderalab/opentis#131]
[mdtraj](http://mdtraj.org) and [msmbuilder](http://msmbuilder.org) have `index.html` documents in their S3 buckets that redirect to `latest/index.html`.  Were these created manually, or is there some automated structure for creating and pushing these to the S3 buckets?

They look like this:
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<!-- <html><head><meta http-equiv=Refresh content="0;url=/latest/"></head></html> -->
<html><head><script>
request = new XMLHttpRequest();
request.open('GET', 'https://api.github.com/repos/SimTk/mdtraj/releases', true);

request.onreadystatechange = function() {
  if (this.readyState === 4){
    if (this.status >= 200 && this.status < 400){
      // Success!
      var data = JSON.parse(this.responseText);
      // get the latest release
      var version = data[0].tag_name;
      window.location.replace("/" + version);
    } else {
        window.location.replace("/latest");
    }
  }
};

request.send();
request = null;
</script></head></html>
```
@rmcgibbo and @kyleabeauchamp : Can you enlighten us?

**Comment by rmcgibbo** [comment]
I'm sure I just wrote it. But it's obviously too old, and brokenish.

**Comment by rmcgibbo** [comment]
I changed them to use redirects on the S3 side using these instructions. http://docs.aws.amazon.com/AmazonS3/latest/dev/how-to-page-redirect.html

**Comment by rmcgibbo** [comment]
Quite a bit faster initial load times now too.

**Comment by jchodera** [comment]
I'm not clear on how that works.  Do you still need a top-level `index.html` that you then set a metadata property for?  Or can you do this even if there is no top-level `index.html`?

**Comment by rmcgibbo** [comment]
not sure. i kept a top level index, but changed it to be a simple meta-refresh redirect.

**Comment by jchodera** [comment]
Thanks for the help!
