### ISSUE TITLE
Project Name

### ISSUE THREAD

**Issue by jhprinz** [choderalab/opentis#56]
Just to collect ideas separately for a while...

About the name. So this package effective allows to sample ensembles of paths. So something with these three words? 
- PathFinder
- PES (PathEnsembleSampling)
 Groups of paths might form a "Flow"?
- FlowSampling

Lots of paths form a street (Autobahn) a map
- PathMapper
- EnsembleMapper
- MapSampler

Cartography?

**Comment by dwhswenson** [comment]
Sounds like we have settled on OpenPathSampling, and @jchodera got us the URL and opened an issue to change the repo name (and with that that, we should change the directory, although we should probably hold off on that until current branches are merged in.)

Anyway, all of that is just to say that I'm closing this issue; remaining aspects are in other issues already open!
