### ISSUE TITLE
Should we use openmmtools.integrators instead of duplicating it here?

### ISSUE THREAD

**Issue by jchodera** [choderalab/opentis#87]
We now have a copy of `integrators` in [`openmmtools.integrators`](https://github.com/choderalab/openmmtools/blob/master/OpenMMTools/integrators.py).  Should we use that instead of the [`integrators.py`](https://github.com/choderalab/opentis/blob/master/opentis/integrators.py) here?  We have to make some changes to the variable names anyway to avoid potential bugs with `CustomForce` systems, so it might be easiest to only maintain one set of these files.

On the other hand, if there's the expectation that a lot of new custom integrators that would not be of general interest might be added, it may be useful to keep a local `integrators.py`.  But for now, this should probably be avoided.

**Comment by jhprinz** [comment]
I added this as a WIP, but we need to have openmmtools installable via conda

**Comment by kyleabeauchamp** [comment]
Should have at least the py27 version available

**Comment by kyleabeauchamp** [comment]
https://binstar.org/omnia/openmmtools/files

**Comment by jhprinz** [comment]
This works now we need to fix MSMBuilder3 changes

**Comment by jhprinz** [comment]
I will remove the multi_RMSD and add a function and test to use MSMBuilder3 featurizers, that is much more convenient.

**Comment by jhprinz** [comment]
Fixed and closed...
